@startuml
!include <archimate/Archimate>

title IT4IT: Explore

Strategy_ValueStream(e_id7fb8e4a3ead059, "IT4IT: Explore") {
  Strategy_ValueStream(e_idb26c47d4351d5f, "Explore: Define Digital Product Architecture")
  Strategy_ValueStream(e_ideb6f10a6249856, "Explore: Refine Product Backlog")
  Strategy_ValueStream(e_id3cce6ddd71a554, "Explore: Prioritize Backlog Items")
  Strategy_ValueStream(e_id5fc8f94282b356, "Explore: Finalize Roadmap & Scope Agreement")
}


@enduml
