@startuml
!include <archimate/Archimate>

title IT4IT: Operate

Strategy_ValueStream(e_idd9aa16f51da958, "IT4IT: Operate") {
  Strategy_ValueStream(e_id61e6c145346959, "Operate: Detect Issue")
  Strategy_ValueStream(e_id7fed31beba0b52, "Operate: Diagnose Issue")
  Strategy_ValueStream(e_id983000175eba5f, "Operate: Resolve Issue")
}


@enduml
