@startuml
!include <archimate/Archimate>

title IT4IT: Value Streams

Strategy_ValueStream(e_idf2e1bcaab0b050, "IT4IT: Value Streams") {
  Strategy_ValueStream(e_id7fb8e4a3ead059, "IT4IT: Explore")
  Strategy_ValueStream(e_id587fca1cae9254, "IT4IT: Evaluate")
  Strategy_ValueStream(e_id3db0cbb3835a52, "IT4IT: Integrate")
  Strategy_ValueStream(e_id2a9a1fcfef0e5f, "IT4IT: Deploy")
  Strategy_ValueStream(e_id2450fe8b5d985b, "IT4IT: Release")
  Strategy_ValueStream(e_idd9aa16f51da958, "IT4IT: Operate")
  Strategy_ValueStream(e_idd3ec795635fd51, "IT4IT: Consume")
}
Motivation_Outcome(e_id98a0748d593250, "IT4IT: Digital Product")

Rel_Realization_Up(e_idf2e1bcaab0b050, e_id98a0748d593250, "")
Rel_Aggregation(e_idd9aa16f51da958, e_idf2e1bcaab0b050, "")
Rel_Flow_Right(e_id2450fe8b5d985b, e_idd3ec795635fd51, "")
Rel_Flow_Right(e_id2a9a1fcfef0e5f, e_id587fca1cae9254, "")
Rel_Flow_Right(e_idd3ec795635fd51, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id7fb8e4a3ead059, e_id3db0cbb3835a52, "")
Rel_Flow_Right(e_id587fca1cae9254, e_idd3ec795635fd51, "")
Rel_Flow_Right(e_id587fca1cae9254, e_id7fb8e4a3ead059, "")
Rel_Flow_Right(e_id587fca1cae9254, e_idd9aa16f51da958, "")
Rel_Flow_Right(e_idd9aa16f51da958, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id2a9a1fcfef0e5f, e_idd9aa16f51da958, "")
Rel_Flow_Right(e_idd3ec795635fd51, e_idd9aa16f51da958, "")
Rel_Flow_Right(e_id3db0cbb3835a52, e_id2a9a1fcfef0e5f, "")
Rel_Flow_Right(e_id587fca1cae9254, e_id2450fe8b5d985b, "")
Rel_Flow_Right(e_id2450fe8b5d985b, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id587fca1cae9254, e_id3db0cbb3835a52, "")
Rel_Flow_Right(e_id3db0cbb3835a52, e_id2450fe8b5d985b, "")
Rel_Flow_Right(e_id7fb8e4a3ead059, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id3db0cbb3835a52, e_id587fca1cae9254, "")
Rel_Flow_Right(e_id587fca1cae9254, e_id2a9a1fcfef0e5f, "")

@enduml
