#!/usr/bin/env python3
"""Import GitHub milestones, issues and releases as an ArchiMate roadmap layer (GH #95).

Reads GitHub through the `gh` CLI and writes `architecture/model/gh-roadmap/`
{elements,relationships,views}.yaml, which `build.py` merges as an optional layer.
The mapping, ids and rules live in specs/003-gh-roadmap-archimate/data-model.md.

    poetry run python architecture/model/import_gh_roadmap.py [--repo OWNER/NAME] [--check]

Exit codes: 0 written or current, 1 `--check` found the layer stale, 2 GitHub data
could not be retrieved or parsed (nothing is written).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

HERE = Path(__file__).parent
LAYER_DIR = HERE / "gh-roadmap"
LAYER_FILES = ("elements.yaml", "relationships.yaml", "views.yaml")
HEADER = b"# Generated by architecture/model/import_gh_roadmap.py from GitHub. Do not edit.\n"

ISSUE_PAGE_SIZE = 100
MAX_ISSUE_PAGES = 10  # research R8: a cap of 1000 issues
WORK_PACKAGE_SLUG_MAX = 40

RunGh = Callable[[list[str]], str]
Layer = dict[str, list[dict[str, Any]]]

ISSUES_QUERY = (
    "query($owner:String!,$name:String!,$after:String){repository(owner:$owner,name:$name){"
    f"issues(first:{ISSUE_PAGE_SIZE},after:$after,states:[OPEN,CLOSED]){{"
    "pageInfo{hasNextPage endCursor} nodes{number title state closedAt url "
    "milestone{number} parent{number} blockedBy(first:50){nodes{number}}}}}}"
)


class GhError(Exception):
    """GitHub data could not be retrieved or understood; the message names the call and the fix."""


@dataclass(frozen=True)
class Milestone:
    number: int
    title: str
    description: str
    state: str
    due_on: str | None
    url: str


@dataclass(frozen=True)
class Release:
    tag: str
    name: str
    body: str
    published_at: str
    url: str


@dataclass(frozen=True)
class Issue:
    number: int
    title: str
    state: str
    closed_at: str | None
    url: str
    milestone: int | None
    parent: int | None
    blocked_by: tuple[int, ...]


# --- slugs and ids (data-model "Element ids") --------------------------------------


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "untitled"


def work_package_slug(title: str) -> str:
    """Slug cut at a word boundary to at most 40 characters; a longer single word is hard-cut."""
    slug = ""
    for word in slugify(title).split("-"):
        candidate = f"{slug}-{word}" if slug else word
        if len(candidate) > WORK_PACKAGE_SLUG_MAX:
            return slug or word[:WORK_PACKAGE_SLUG_MAX]
        slug = candidate
    return slug


def plateau_id(title: str, number: int) -> str:
    return f"plat-{slugify(title)}-{number}"


def release_id(tag: str) -> str:
    return f"del-release-{slugify(tag)}"


def planned_id(title: str, number: int) -> str:
    return f"del-{slugify(title)}-{number}-planned"


def work_package_id(title: str, number: int) -> str:
    return f"wp-{work_package_slug(title)}-gh-{number}"


# --- gh access ---------------------------------------------------------------------


def run_gh(args: list[str]) -> str:
    call = "gh " + " ".join(args)
    try:
        done = subprocess.run(["gh", *args], capture_output=True, text=True, check=False)
    except FileNotFoundError:
        raise GhError(f"`{call}` failed: the gh CLI is not installed. Install it from https://cli.github.com") from None
    if done.returncode != 0:
        raise GhError(f"`{call}` failed: {done.stderr.strip()}. Check `gh auth status`, or run `gh auth login`.")
    return done.stdout


def _parse(raw: str, call: str) -> Any:
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:
        raise GhError(
            f"`{call}` returned output that is not JSON ({exc.msg}); retry, or run `gh auth status`"
        ) from None


def _rest_items(gh: RunGh, repo: str, collection: str, query: str = "") -> list[dict[str, Any]]:
    call = f"gh api repos/{repo}/{collection}"
    path = f"{call[len('gh api ') :]}?{query + '&' if query else ''}per_page=100"
    pages = _parse(gh(["api", "--paginate", "--slurp", path]), call)
    if not isinstance(pages, list):
        raise GhError(f"`{call}` returned {collection} in an unexpected shape")
    items = [item for page in pages for item in (page if isinstance(page, list) else [page])]
    if not all(isinstance(item, dict) for item in items):
        raise GhError(f"`{call}` returned {collection} in an unexpected shape")
    return items


def fetch_milestones(gh: RunGh, repo: str) -> list[Milestone]:
    items = _rest_items(gh, repo, "milestones", "state=all")
    try:
        return [
            Milestone(
                int(m["number"]), m["title"], m.get("description") or "", m["state"], m.get("due_on"), m["html_url"]
            )
            for m in items
        ]
    except (KeyError, TypeError, ValueError):
        raise GhError(f"`gh api repos/{repo}/milestones` returned milestones missing expected fields") from None


def fetch_releases(gh: RunGh, repo: str) -> list[Release]:
    items = _rest_items(gh, repo, "releases")
    try:
        return [
            Release(r["tag_name"], r.get("name") or "", r.get("body") or "", r["published_at"], r["html_url"])
            for r in items
            if not r["draft"] and not r["prerelease"]
        ]
    except (KeyError, TypeError):
        raise GhError(f"`gh api repos/{repo}/releases` returned releases missing expected fields") from None


def _issue(node: dict[str, Any]) -> Issue:
    return Issue(
        number=int(node["number"]),
        title=node["title"],
        state=node["state"].lower(),
        closed_at=node.get("closedAt"),
        url=node["url"],
        milestone=(node.get("milestone") or {}).get("number"),
        parent=(node.get("parent") or {}).get("number"),
        blocked_by=tuple(int(b["number"]) for b in node["blockedBy"]["nodes"]),
    )


def fetch_issues(gh: RunGh, repo: str) -> list[Issue]:
    """One paginated GraphQL query; fails rather than import a partial set (research R8)."""
    owner, name = repo.split("/", 1)
    call = f"gh api graphql (issues of {repo})"
    issues: list[Issue] = []
    cursor: str | None = None
    for _ in range(MAX_ISSUE_PAGES):
        args = ["api", "graphql", "-f", f"query={ISSUES_QUERY}", "-F", f"owner={owner}", "-F", f"name={name}"]
        if cursor:
            args += ["-f", f"after={cursor}"]
        try:
            page = _parse(gh(args), call)["data"]["repository"]["issues"]
            issues += [_issue(n) for n in page["nodes"]]
            has_next, cursor = page["pageInfo"]["hasNextPage"], page["pageInfo"]["endCursor"]
        except (KeyError, TypeError, ValueError, AttributeError):
            raise GhError(f"`{call}` returned issues missing expected fields") from None
        if not has_next:
            return issues
    cap = ISSUE_PAGE_SIZE * MAX_ISSUE_PAGES
    raise GhError(f"`{call}`: {repo} has more than {cap} issues, the import cap; raise MAX_ISSUE_PAGES deliberately")


# --- the layer ---------------------------------------------------------------------


PLATEAU_TOKEN = re.compile(r"(?<![\w-])plat-[a-z0-9-]+")
FUNCTION_TOKEN = re.compile(r"(?<![\w-])bfn-[a-z0-9-]+")
# ArchiMate 3.2 section 3.5 derivation: the subset of types check_derived.py also auto-checks,
# strongest first. A link is implied when two shorter links chain to it with that weaker type.
STRENGTH = ["Composition", "Aggregation", "Assignment", "Realization", "Serving", "Triggering", "Flow"]
RANK = {name: i for i, name in enumerate(STRENGTH)}


def load_business_functions(path: Path = HERE / "elements.yaml") -> frozenset[str]:
    """Ids of the hand-authored BusinessFunctions a milestone description may name."""
    return frozenset(e["id"] for e in yaml.safe_load(path.read_text()) if e.get("type") == "BusinessFunction")


def _props(**values: str | None) -> dict[str, str]:
    return {key.replace("_", "-"): value for key, value in sorted(values.items()) if value}


def _element(type_: str, id_: str, name: str, desc: str = "", props: dict[str, str] | None = None) -> dict[str, Any]:
    element: dict[str, Any] = {"type": type_, "id": id_, "name": name}
    if desc:
        element["desc"] = desc
    if props:
        element["props"] = props
    return element


def _link(type_: str, source: str, target: str) -> dict[str, str]:
    return {"type": type_, "source": source, "target": target}


def _tokens(pattern: re.Pattern[str], text: str, known: frozenset[str] | set[str]) -> list[str]:
    """Ids in free text that exactly match an existing element of the right type (FR-006)."""
    return sorted(set(pattern.findall(text)) & known)


def _plateaus(
    milestones: list[Milestone], functions: frozenset[str]
) -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    elements, rels = [], []
    for m in milestones:
        pid = plateau_id(m.title, m.number)
        props = _props(gh_number=str(m.number), gh_url=m.url, gh_state=m.state, gh_due=m.due_on)
        elements.append(_element("Plateau", pid, m.title, m.description, props))
        rels += [_link("Realization", pid, f) for f in _tokens(FUNCTION_TOKEN, m.description, functions)]
    return elements, rels


def _releases(
    releases: list[Release], plateaus: set[str]
) -> tuple[list[dict[str, Any]], list[dict[str, str]], dict[str, list[Release]]]:
    """Release Deliverables, their Realization of named Plateaus, and the releases per Plateau in publish order."""
    elements, rels = [], []
    per_plateau: dict[str, list[Release]] = {}
    for r in sorted(releases, key=lambda r: (_when(r.published_at), r.tag)):
        did = release_id(r.tag)
        props = _props(gh_tag=r.tag, gh_url=r.url, gh_published=r.published_at)
        elements.append(_element("Deliverable", did, r.name or r.tag, props=props))
        for pid in _tokens(PLATEAU_TOKEN, r.body, plateaus):
            rels.append(_link("Realization", did, pid))
            per_plateau.setdefault(pid, []).append(r)
    return elements, rels, per_plateau


def _when(stamp: str) -> datetime:
    return datetime.fromisoformat(stamp)


def _deliverable_for(issue: Issue, pid: str, planned: str, per_plateau: dict[str, list[Release]]) -> str:
    """Open: the planned Deliverable. Closed: the first release published after closing, else planned."""
    if issue.state == "closed" and issue.closed_at:
        closed = _when(issue.closed_at)
        for release in per_plateau.get(pid, []):
            if _when(release.published_at) > closed:
                return release_id(release.tag)
    return planned


def drop_derived(rels: list[dict[str, str]]) -> list[dict[str, str]]:
    """Drop a link that two shorter importer-emitted links already imply (FR-004, derivation rule)."""
    kept = sorted(rels, key=_sort_key)
    out: dict[str, list[dict[str, str]]] = {}
    for rel in kept:
        out.setdefault(rel["source"], []).append(rel)
    for rel in list(kept):
        if _implied(rel, out):
            kept.remove(rel)
            out[rel["source"]].remove(rel)
    return kept


def _implied(rel: dict[str, str], out: dict[str, list[dict[str, str]]]) -> bool:
    for first in out.get(rel["source"], []):
        if first is rel or first["target"] in (rel["source"], rel["target"]) or first["type"] not in RANK:
            continue
        for second in out.get(first["target"], []):
            if second["target"] == rel["target"] and second["type"] in RANK:
                if max(first["type"], second["type"], key=RANK.__getitem__) == rel["type"]:
                    return True
    return False


def build_layer(
    milestones: list[Milestone],
    releases: list[Release],
    issues: list[Issue],
    business_functions: frozenset[str] = frozenset(),
) -> Layer:
    elements, rels = _plateaus(milestones, business_functions)
    plateau_by_number = {m.number: plateau_id(m.title, m.number) for m in milestones}
    release_elements, release_rels, per_plateau = _releases(releases, set(plateau_by_number.values()))
    elements, rels = elements + release_elements, rels + release_rels

    in_scope = {i.number: i for i in issues if i.milestone in plateau_by_number}
    planned_for: set[int] = set()
    for issue in in_scope.values():
        assert issue.milestone is not None
        pid, wid = plateau_by_number[issue.milestone], work_package_id(issue.title, issue.number)
        planned = planned_id(_title(milestones, issue.milestone), issue.milestone)
        target = _deliverable_for(issue, pid, planned, per_plateau)
        elements.append(
            _element(
                "WorkPackage", wid, f"GH-{issue.number} {issue.title}",
                props=_props(gh_number=str(issue.number), gh_url=issue.url, gh_state=issue.state),
            )
        )  # fmt: skip
        rels.append(_link("Realization", wid, target))
        if target == planned:
            planned_for.add(issue.milestone)
    rels += _dependencies(in_scope, plateau_by_number)
    for number in sorted(planned_for):
        title = _title(milestones, number)
        elements.append(
            _element("Deliverable", planned_id(title, number), f"{title} (planned)", props={"gh-number": str(number)})
        )
        rels.append(_link("Realization", planned_id(title, number), plateau_by_number[number]))
    return {
        "elements.yaml": elements,
        "relationships.yaml": drop_derived(rels),
        "views.yaml": _views(milestones, elements, rels),
    }


def _dependencies(in_scope: dict[int, Issue], plateau_by_number: dict[int, str]) -> list[dict[str, str]]:
    """Triggering from blockers, Aggregation from parents, lifted to Plateaus; unimported ends are dropped."""
    rels: list[dict[str, str]] = []
    plateau_links: set[tuple[str, str]] = set()
    for issue in in_scope.values():
        wid = work_package_id(issue.title, issue.number)
        for number in issue.blocked_by:
            blocker = in_scope.get(number)
            if blocker is None:
                continue
            rels.append(_link("Triggering", work_package_id(blocker.title, blocker.number), wid))
            assert blocker.milestone is not None and issue.milestone is not None
            if blocker.milestone != issue.milestone:
                plateau_links.add((plateau_by_number[blocker.milestone], plateau_by_number[issue.milestone]))
        parent = in_scope.get(issue.parent) if issue.parent is not None else None
        if parent is not None:
            rels.append(_link("Aggregation", work_package_id(parent.title, parent.number), wid))
    return rels + [_link("Triggering", source, target) for source, target in sorted(plateau_links)]


def _title(milestones: list[Milestone], number: int) -> str:
    return next(m.title for m in milestones if m.number == number)


def _views(
    milestones: list[Milestone], elements: list[dict[str, Any]], rels: list[dict[str, str]]
) -> list[dict[str, Any]]:
    """One roadmap view per milestone: its Plateau, the Deliverables realizing it and their Work Packages (R11)."""
    realizes: dict[str, set[str]] = {}
    for rel in rels:
        if rel["type"] == "Realization":
            realizes.setdefault(rel["target"], set()).add(rel["source"])
    ids = {e["id"] for e in elements}
    views = []
    for m in milestones:
        pid = plateau_id(m.title, m.number)
        deliverables = {d for d in realizes.get(pid, set()) if d in ids and d.startswith("del-")}
        packages = {w for d in deliverables for w in realizes.get(d, set()) if w.startswith("wp-")}
        views.append(
            {
                "id": f"view-{pid}",
                "name": f"Roadmap: {m.title}",
                "viewpoint": "implementation_migration",
                "diagram": f"migration/{pid}",
                "members": sorted({pid, *deliverables, *packages}),
            }
        )
    return views


def _sort_key(item: dict[str, Any]) -> tuple[str, ...]:
    if "source" in item:
        return (item["type"], item["source"], item["target"], item.get("label", ""))
    return (item.get("type", ""), item["id"])


def render_layer(layer: Layer) -> dict[str, bytes]:
    """Sorted, timestamp-free YAML bytes per file, so unchanged GitHub state is byte-identical."""
    return {
        name: HEADER
        + yaml.safe_dump(
            sorted(layer[name], key=_sort_key),
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
            width=10**6,
        ).encode()
        for name in LAYER_FILES
    }


def _previous(path: Path) -> bytes | None:
    return path.read_bytes() if path.exists() else None


def write_layer(files: dict[str, bytes], directory: Path) -> None:
    """Replace the layer only after every file rendered; on a failure restore what was there."""
    directory.mkdir(parents=True, exist_ok=True)
    targets = {name: directory / name for name in files}
    before = {name: _previous(path) for name, path in targets.items()}
    temps = {name: path.with_name(path.name + ".tmp") for name, path in targets.items()}
    try:
        for name, temp in temps.items():
            temp.write_bytes(files[name])
        for name, temp in temps.items():
            os.replace(temp, targets[name])
    except OSError:
        for name, path in targets.items():
            previous = before[name]
            if previous is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(previous)
        raise
    finally:
        for temp in temps.values():
            temp.unlink(missing_ok=True)


def _summary(layer: Layer) -> str:
    kinds = [e["type"] for e in layer["elements.yaml"]]
    triggers = sum(1 for r in layer["relationships.yaml"] if r["type"] == "Triggering")
    planned = sum(1 for e in layer["elements.yaml"] if e["id"].endswith("-planned"))
    return (
        f"gh-roadmap: {kinds.count('Plateau')} milestones, {kinds.count('Deliverable') - planned} releases, "
        f"{planned} planned deliverable{'' if planned == 1 else 's'}, {kinds.count('WorkPackage')} work packages, "
        f"{triggers} triggering"
    )


def main(argv: list[str] | None = None, run_gh: RunGh = run_gh, layer_dir: Path = LAYER_DIR) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0] if __doc__ else None)
    parser.add_argument("--repo", metavar="OWNER/NAME", help="repository to read (default: the one gh resolves here)")
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 if the layer is stale")
    args = parser.parse_args(argv)
    try:
        repo = args.repo or run_gh(["repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"]).strip()
        layer = build_layer(
            fetch_milestones(run_gh, repo),
            fetch_releases(run_gh, repo),
            fetch_issues(run_gh, repo),
            load_business_functions(),
        )
    except GhError as exc:
        sys.stderr.write(f"error: {exc}\n")
        return 2
    files = render_layer(layer)
    current = all(_previous(layer_dir / name) == data for name, data in files.items())
    if args.check:
        print("gh-roadmap: current" if current else "gh-roadmap: stale, re-run the importer")
        return 0 if current else 1
    if current:
        print("gh-roadmap: unchanged")
        return 0
    write_layer(files, layer_dir)
    print(f"wrote {_summary(layer)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
